import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import Header from '@/components/Header'


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Coworking App",
  description: "Generated by Leiziane",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
<>

 <Header/>
     
        <main className="flex flex-1 flex-col">
        
        {children}
        </main>

  </>
   
  );
}
