import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import DashboardHeader from "@/components/DashboardHeader";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Coworking App",
  description: "Generated by Leiziane",
};

export default function DashLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
    
    
    <DashboardHeader />
     
        <main className="flex flex-1 flex-col">
        {children}
        </main>

    </>
    
   
  );
}
